name: novablue_appointment_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supabase_flutter: ^2.0.2
  flutter_riverpod: ^2.4.5
  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  iconly: ^1.0.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true

  uses-material-design: true

  assets:
    - images/logos/
    - images/undraw/
    - images/main/

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Regular.ttf
        - asset: fonts/Urbanist-Medium.ttf
        - asset: fonts/Urbanist-Bold.ttf
        - asset: fonts/Urbanist-SemiBold.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff"
  image: images/logos/medica_horizontal.png # This should be 1152×1152 pixels, and fit within a circle 768 pixels in diameter.

  android_12:
    color: "#ffffff"
    image: images/logos/medica_horizontal.png # This should be 1152×1152 pixels, and fit within a circle 768 pixels in diameter.
